name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          output: dist/snake.svg

      - name: Push the Snake to the output branch
        uses: actions/upload-artifact@v2
        with:
          name: snake
          path: dist/snake.svg
